### ISSUE TITLE
在shell窗口执行 CTRL + L 快捷键清理屏幕，窗口会无法使用

### ISSUE THREAD

**Issue by fcxjluo** [1Panel-dev/webkubectl#53]
connect打开新窗口后，执行一些命令，窗口输出内容后，执行CTRL + L 快捷键，窗口会无法使用
![image](https://github.com/user-attachments/assets/384d5d79-bd63-4ac4-b096-b14af2539cb7)
![image](https://github.com/user-attachments/assets/d0e66f0a-56a8-42cb-95b4-07b4a8510514)

**Comment by liqiang-fit2cloud** [comment]
我这没问题啊。

https://github.com/user-attachments/assets/bd7634d2-194c-41cf-afdb-f192b7875079

**Comment by fcxjluo** [comment]
我这边大概率会出现

https://github.com/user-attachments/assets/cf9ff78e-96ad-4bde-9645-0a2aa75e846d
consolebao报这个错误

Uncaught Error: Could not release an element not yet acquired
    at e.release (gotty-bundle.js:88:64683)
    at e._refresh (gotty-bundle.js:88:43942)
    at e._refreshLoop (gotty-bundle.js:88:43139)
